### ISSUE TITLE
Is it possible for SetUpTest *C to return the test it is is setting up from TestName() 

### ISSUE THREAD

**Issue by levpaul** [go-check/check#11]
I would like to use the TestName() of the tests I'm about to run inside the SetUpTest method. Can we do this? Could we just feed it in somehow?

**Comment by niemeyer** [comment]
That's how I assumed the proposed implementation was working, but I see it's not. I'll fix it.

**Comment by levpaul** [comment]
Cheers!

**Comment by levpaul** [comment]
So your fix is working, in terms of the test name. I'm seeing behaviour now where one of my tests is being run twice... Is it possible that this patch could have triggered such a thing?

I haven't checked if the behaviour existed prior to the patch, but I can do so if you like.

**Comment by niemeyer** [comment]
No, that's unrelated. Please try to reproduce it with a small test case.

**Comment by levpaul** [comment]
Damn, I tried to reproduce with a small test case but couldn't. In my larger case I add a time.Sleep(time.Minute) into my test and the test suite takes an extra 2 minutes to run (The failed test only takes 1 minute, I guess the first run passes).

Anyway, I checkout out the previous commit of go-check and it made no difference. I need to sleep now, but I'll dig into this more tomorrow night.

**Comment by niemeyer** [comment]
There are simpler ways to check whether it's running twice, such as printing a line when it runs.

Also worth checking if the same suite is not being registered twice.

**Comment by levpaul** [comment]
Good point with the simpler checks. I've managed to reproduce it any way and have opened up [issue 12](https://github.com/go-check/check/issues/12)
