### ISSUE TITLE
Stop using gopkg.in

### ISSUE THREAD

**Issue by djmitche** [go-check/check#116]
It looks lke gopkg.in is having issues: https://github.com/niemeyer/gopkg/issues/67.  There's a stunning silence from the gopkg.in maintainers on that issue.  We have been forced to work around this [using `replace` declarations in our application](https://github.com/taskcluster/taskcluster/pull/1354/files)

Please consider making the package path for yaml `github.com/go-check/check`, perhaps for a new major version.

**Comment by niemeyer** [comment]
I will talk to the gopkg.in maintainer. :)
