### ISSUE TITLE
Multiple test files in same package run some tests twice

### ISSUE THREAD

**Issue by levpaul** [go-check/check#12]
Okay, so I've managed to reproduce this in a simple test case. Basically it seems like when I have two different test files in the same directory, same package and run `go test -v ./...` the second test file which is run executes the tests from the first test file's suite _alongside_ its own suite's tests.

Below is a small example, just create both files in the same directory and run `go test ./...`. The output should show SuiteOne outputting TESTONE and then SuiteTwo outputting TESTONE _and_ TESTTWO.

FILE - onetest.go

``` go
package session

import (
  . "gopkg.in/check.v1"
  "fmt"
  "testing"
)

type SuiteOne struct { }

func TestOne(t *testing.T) {
  Suite(&SuiteOne{})
  TestingT(t)
}

func (t *SuiteOne) TestOne(c *C) {
  fmt.Println("TESTONE")
}
```

FILE - twotest.go

``` go
package session

import (
  . "gopkg.in/check.v1"
  "fmt"
  "testing"
)


type SuiteTwo struct { }

func TestTwo(t *testing.T) {
  Suite(&SuiteTwo{})
  TestingT(t)
}

func (t *SuiteTwo) TestTwo(c *C) {
  fmt.Println("TESTTWO")
}
```

The output looks like this:

``` bash
$ go test -v ./...
=== RUN TestOne
TESTONE
OK: 1 passed
--- PASS: TestOne (0.00 seconds)
=== RUN TestTwo
TESTONE
TESTTWO
OK: 2 passed
--- PASS: TestTwo (0.00 seconds)
PASS
ok      _/Users/llovelock/test/check    0.014s
```

Any idea of what's going on here?

**Comment by niemeyer** [comment]
TestingT must be called a single time for tests in the whole package. Every time you call it will do exactly the same thing.

**Comment by levpaul** [comment]
Hmm. So where would you recommend I add the TestingT call? And from there, does it mean I need to re-add that call to each test file if I want to run those tests independently?

**Comment by niemeyer** [comment]
Please see the page for the project:

http://labix.org/gocheck

I should make that more clear in the API docs.

**Comment by levpaul** [comment]
Yeah, I agree. I had no idea. I'm glad you spotted it at least. I'm not aware of the underlying architecture, but would it be reasonable to raise an issue to make multiple calls to TestingT per package _not_ rerun the Suites that were registered from previous test files within that package? Can't the suite contain some information about which file it was registered with or something?

**Comment by niemeyer** [comment]
The design is fairly clean and properly orthogonal. TestingT simply calls a runner with a set of options, and it runs the suites registered. You can do that yourself if you wish, as these are part of the public API, but I'd prefer to not start saving global state across runs without a good enough reason. This is the first time I've heard of this issue in the years gocheck has been around.

**Comment by levpaul** [comment]
I really wonder why. Is it just that people don't run multiple test files for the same package? Or maybe that each test completely removes its state? I may look into making the changes, as it feels like a smell calling TestingT from only one of the test files per package.

**Comment by niemeyer** [comment]
Go doesn't give special meaning to file context, whether in tests or not. TestingT was not designed to be different, or any of gocheck really.

**Comment by levpaul** [comment]
I can understand that. This is unit testing though. Having different files in the same package and different test files too isn't unexpected. Take a look at packer for example. There are a LOT of different files per package, including tests. Although, I don't know the reason why they've decided to stay with the vanilla "testing" framework.

**Comment by levpaul** [comment]
I just took a look at your source. I think I'll just end up doing something like what you're doing, per package:

``` go
// We count the number of suites run at least to get a vague hint that the
// test suite is behaving as it should.  Otherwise a bug introduced at the
// very core of the system could go unperceived.
const suitesRunExpected = 8

var suitesRun int = 0

func Test(t *testing.T) {
    check.TestingT(t)
    if suitesRun != suitesRunExpected && flag.Lookup("check.f").Value.String() == "" {
        critical(fmt.Sprintf("Expected %d suites to run rather than %d",
            suitesRunExpected, suitesRun))
    }
}
```

It at least is making it explicit the TestingT call is a form of central control.

**Comment by niemeyer** [comment]
You took that out of the test suite of gocheck, which is a great example for how to write a testing package that tests itself, but not a great example of how to use that testing package. Everywhere else I assume that gocheck works, rather than writing that kind of ugly hackery.

See gopkg.in/yaml.v1 if you want a more realistic example of normal use cases.

**Comment by levpaul** [comment]
Cool. I think the yaml solution will work for me. I still want separate suites for each test file, but having a separate test to declare the suite structs and make the TestingT call is not that bad.

**Comment by niemeyer** [comment]
There's no need to declare suites inside a test.

**Comment by levpaul** [comment]
... I assume Suites are objects which the runner goes through and finds all the appropriate test functions on it to run. One thing I'm confused about is the `var _ = Suite(S{})` <- that looks like you're declaring a suite in a test file to me.

**Comment by niemeyer** [comment]
As I said before, Go does not attribute special meaning to files. Distribute content across files as appropriate for a good design.

The var _ line does exactly the same as running the Suite call within an init() function.
