### ISSUE TITLE
Better test logging for -v

### ISSUE THREAD

**Issue by zealws** [go-check/check#13]
When the `-v` flag is used, the test reporting is very difficult to read. It is basically the stdout/err of every test combined without any information about which tests are running.

I think check should probably print some more details if the `-v` flag is given. Definitely the name of the test suite and function. Probably also the filename of the test.

The state of the flag can be retrieved through the [testing.Verbose function](http://golang.org/pkg/testing/#Verbose).

**Comment by niemeyer** [comment]
There's a verbose flag specific to gocheck: -check.v

**Comment by zealws** [comment]
That doesn't seem to work if the project has compile failures.

```
$ go test -check.v my-project-url
can't load package: package my-project-url: no buildable Go source files in my-gopath/my-project-url
$ go test my-project-url
# my-project-url
... compile failures
FAIL    my-project-url [build failed]
```

**Comment by zealws** [comment]
It doesn't work when there are no compile errors either:

```
$ go test -check.v my-project-url
can't load package: package my-project-url: no buildable Go source files in my-gopath/my-project-url
$ go test my-project-url
ok      my-project-url  2.165s
```

**Comment by niemeyer** [comment]
Actually, the difference is that it stops parsing on the first unknown flag. Try this:

```
go test my-project-url -check.v
```

**Comment by zealws** [comment]
Putting the `-check.v` after the url appears to work, I'll use that instead.

Thanks!

**Comment by zealws** [comment]
Note that in order for it to work correctly you have to provide both `-v` and `-check.v`.

Otherwise, `testing` will hide the verbose output of the check framework.

```
go test -v my-project-url -check.v
```

**Comment by niemeyer** [comment]
You don't have to provide both at the same time, unless you want the effect of both. I pretty much never use -v, but use -check.v frequently, for example.
