### ISSUE TITLE
Tests don't compile

### ISSUE THREAD

**Issue by freeeve** [go-check/check#2]
There are references to functions that used to be public but aren't (presumably), so they don't compile. Maybe these functions shouldn't be tested from check_test anymore?

```
(v1 ✓) wes-macbook:check go test
# github.com/wfreeman/check_test
./printer_test.go:81: undefined: PrintLine
./printer_test.go:100: undefined: Indent
FAIL    github.com/wfreeman/check [build failed]
```

**Comment by AlekSi** [comment]
This works for me:

``` bash
go get -u gopkg.in/check.v1
cd $GOPATH/src/gopkg.in/check.v1
go test
```

**Comment by freeeve** [comment]
Indeed. Thanks for pointing that out... I now see that they're defined in export_test.go--still not sure why it's failing in my fork, but clearly it's not an issue with a clean clone.
