### ISSUE TITLE
godoc broken?

### ISSUE THREAD

**Issue by jbenet** [go-check/check#24]
![](https://www.evernote.com/shard/s198/sh/3c73ba15-0948-4696-afe3-b0a064bde895/6772f4d5123b629d56513711d1bc9c7f/deep/0/error---GoDoc.png)

**Comment by niemeyer** [comment]
The import path is gopkg.in/check.v1:

https://godoc.org/gopkg.in/check.v1

**Comment by jbenet** [comment]
@niemeyer ok. you can't control what people might use to import and refer to your packages. You can try to force one way or another, but invariably there will be confusion.

**Comment by niemeyer** [comment]
Actually, I can. Try to use the wrong import path and you'll get an error as well.

**Comment by niemeyer** [comment]
Please note that this is also quite well documented.

**Comment by jbenet** [comment]
> Actually, I can. ... **wrong** import path

What if I don't trust your `gopkg.in` url to remain up forever, and prefer to use github? There's many other reasons to prefer so, like contributing. Or exploring all the branches. It's not _wrong_, just not _your_ preference. I can easily:

```
git clone https://github.com/go-check/check $GOPATH/pkg/github.com/go-check/check
cd $GOPATH/pkg/github.com/go-check/check
git checkout v1
```

``` Go
import check "github.com/go-check/check"
```

And satisfy my preference.

Look, I'm all for package managers. I myself want one to exist for Go. And it's perhaps an annoying, unintentional side effect that -- when a user finds your package on github and simply goes to the usual and __expected__ https://godoc.org/github.com/go-check/check (by habit, or because tools / extensions make these assumptions about Go code) -- one sees this confusing error page. I obviously didn't get there because i _wanted_ to find an error.

It's also clearly not well documented:

![](https://www.evernote.com/shard/s198/sh/8bb1584b-ef6e-44e2-98ed-d1e4005caa3f/eee6be8661467ebc998c7e5747404a6e/deep/0/error---GoDoc.png)

No mention of what's up. Simply something that looks clearly wrong.  I suggest you add a comment, like:

```
// Package error is a placeholder. The preferred import path is "gopkg.in/check.v1", 
// and thus the correct documentation is at https://godoc.org/gopkg.in/check.v1
// Please see http://gopkg.in for more information about this service.
package error
```

**Comment by niemeyer** [comment]
It's not clear what you're really complaing about, or what you are trying to achieve. You want to fork it because some day you may have to fork it because gopkg.in may not be around? That makes no sense to me.

Either way, please feel free to do anything the license allows you to do, which is almost anything. If you use it from this repository, though, I ask you to please use the official import path or it will not work.

Thank you.
