### ISSUE TITLE
gocheck doesn't work with -test.run="..."

### ISSUE THREAD

**Issue by mpobrien** [go-check/check#27]
I frequently use the `-test.run=` argument with `go test` if i'm only interested in running a single test in the test suite, which is really useful when the entire test suite takes a long time to run and I'm only working on a single test at a time.

 I noticed that with gocheck this flag seems to have no effect (i'm running it with `gocheck -gocheck.v -test.run="TestName"`) as it always prints `PASS` immediately and doesn't run any tests at all. Is there a way to get this flag to work, or an alternate way of accomplishing the same thing with gocheck?

**Comment by niemeyer** [comment]
The flag for filtering gocheck tests is -check.f (or -gocheck.f, for compatibility purposes).

-test.run is handled by the testing package, and there's no way to override it politely.

**Comment by mpobrien** [comment]
Ah, I missed this in the docs, but I see it now - thanks!
