### ISSUE TITLE
Description for a test

### ISSUE THREAD

**Issue by sejoharp** [go-check/check#32]
Hello,

is it possible to descibe a test? I like gocheck but I miss a way to describe what a method is testing with a sentence. Am I right that the method name and the suite name are the only ways to describe the tests?

**Comment by niemeyer** [comment]
I would certainly encourage using a comment to describe what any non-obvious test is doing, as usual for pretty much any code. When using the data/table style of test, you can also use a summary as one of the fields in the test struct.
