### ISSUE TITLE
RFC: Implement new Assert functions that support messages for failure

### ISSUE THREAD

**Issue by dlsniper** [go-check/check#37]
I'd like to work on adding new methods with the following signatures:

``` go
Check(obtained interface{}, checker Checker, failureMessage string, args ...interface{}) bool
Assert(obtained interface{}, checker Checker, failureMessage string, args ...interface{})
```

This way, if a test fails it would print a custom message which could be for example the index of the loop the test is currently asserting or some additional debug information that could be used to trace why the assertion failed.

What do you think?

**Comment by niemeyer** [comment]
Please have a look at [Commentf](https://gopkg.in/check.v1#Commentf).

I believe it does exactly what you want.
