### ISSUE TITLE
Setup for all the test suites

### ISSUE THREAD

**Issue by shuhaowu** [go-check/check#4]
For each package, each file has its own test suite. Is there a way to have a common setup for all of the suites?

Right now they all share a common database to operate on.

Furthurmore, can you share context between packages?

**Comment by niemeyer** [comment]
You can do a setup for all the test suites by running logic around the call that hooks gocheck into the traditional go test testing module (check.TestingT), or even by having global (race-safe) logic that is invoked by the suite SetUpSuite method.

I'm tempted to resist doing much more than this in terms of cross-test-suite logic, as it presumes that every single suite must necessarily be setup in the same way. In my experience that's very often not the case, and encouraging people to have such global setup would just incur in unnecessary time penalties.
