### ISSUE TITLE
License information is not provided for benchmark.go

### ISSUE THREAD

**Issue by strikov-canonical** [go-check/check#40]
Hi check team!

File benchmark.go has been taken from golang project and contains proper copyright notice.
Together with copyright notice this file contains the following license information:
'Use of this source code is governed by a BSD-style license that can be found in the LICENSE file'
This statement seems to be wrong because the LICENSE file provided by go-check project contains 2-clause BSD license:

<...>
1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
<...>

while benchmark.go was initially licensed under 3-clause BSD license which can be found here:
https://github.com/golang/go/blob/master/LICENSE

<...>
- Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above
  copyright notice, this list of conditions and the following disclaimer
  in the documentation and/or other materials provided with the
  distribution.
- Neither the name of Google Inc. nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

<...>

I think that you may want to add Golang's LICENSE file to the project as LICENCE.golang
and put a link to it from benchmark.go.

Thanks for helping!
Oleg

**Comment by niemeyer** [comment]
Thanks for reporting this inconsistency.
