### ISSUE TITLE
Can this be considered a dead project?

### ISSUE THREAD

**Issue by dlsniper** [go-check/check#42]
Hi there,

There are quite a few open issues / PRs that have yet to receive input (either comments or be merged / rejected). Can we consider this project dead? Are you interested in help maintaining it if not (I'm volunteering to help out).

Thank you!

**Comment by niemeyer** [comment]
No, this is not a dead project.

**Comment by niemeyer** [comment]
And yes, I am interested in help maintaining it. I'm sorry for taking too long to respond to issues. I just have too much on my plate, and have been unable to provide the proper feedback timely. But this is in use in several important projects I care about, and I still use it pretty much every day.
