### ISSUE TITLE
 Random number generator is not seeded, leading to known paths

### ISSUE THREAD

**Issue by sparkiegeek** [go-check/check#45]
(copied with updates from http://pad.lv/1297690)

go-check uses temporary directories to run tests in, but these temporary directories are made with known, predictable names.

We can see here

https://github.com/go-check/check/blob/v1/check.go#L133

that `newPath` uses `rand.Int()` without first seeding the RNG. Meaning I'll always have tests run in `/tmp/gocheck-5577006791947779410`.

I don't think cryptographically secure random numbers are needed so something as simple as `rand.Seed(time.Nanoseconds())` would probably do the job.

**Comment by jhenstridge** [comment]
The simplest solution would probably be to replace the problem code with a call to `ioutil.TempDir`.  It looks like it avoids the predictable sequence problem.

**Comment by niemeyer** [comment]
Yeah, sounds good.
