### ISSUE TITLE
Ability to get test name inside test

### ISSUE THREAD

**Issue by joeshaw** [go-check/check#5]
I'd like to be able to access the test name inside the test.  Would you be willing to expose  `c.method.String()` method via a method on the `C` type?

**Comment by niemeyer** [comment]
Hi Joe,

What's the use case?

**Comment by joeshaw** [comment]
I'm connecting to a Postgres database and using a different schema per test.  Right now I am generating a random string for that schema name, but a name that I could associate closely with a test would be more helpful when trying to debug a problem across a wide number of tests.

Another use case I had in mind would be to do tracking of success/failure outside of the regular gocheck reporting.  For instance, sending success/failure counts to a statsd server.  If you had the test name you could add code to the suite's `TearDownTest` without needing to touch every test function.

**Comment by niemeyer** [comment]
Sounds good. We can add a C.TestName method which returns the test name ("SuiteName.TestName").
