### ISSUE TITLE
Severe performance regression with c.Assert()

### ISSUE THREAD

**Issue by lupine** [go-check/check#59]
Hi there,

Earlier this year, I had occasion to write some tests with gocheck and go 1.3 that happened to involve calling c.Assert() 67,108,864 (8192*8192) times in a loop. I don't have exact timings but it was fast enough for me not to care.

Re-running those tests now with go1.4 or go1.5 and most recent gocheck (I've not managed to check against go1.3, I'm afraid), they now take ~40 seconds. 

Here's a simple testcase, with the number of iterations whacked down a bit:

```
package mytest_test

import (
    . "gopkg.in/check.v1"
    "testing"
)

type MySuite struct {}
var _ = Suite(&MySuite{})
func Test(t *testing.T) { TestingT(t) }

const Iterations = 8192*1024

func (s *MySuite) TestAssertEqualsSpeed(c *C) {
    for i := 0; i < Iterations; i++ {
        c.Assert(1, Equals, 1)
    }
}

func (s *MySuite) TestAssertIsNilSpeed(c *C) {
    for i := 0; i < Iterations; i++ {
        c.Assert(nil, IsNil)
    }
}

func (s *MySuite) TestOrdinaryComparisonSpeed(c *C) {
    for i := 0; i < Iterations; i++ {
        _ = (1 == 1)
    }
}
```

And the output:

```
[lupine@nlwork2 mytest]$ go test ./... -v -check.v -check.vv
=== RUN Test
START: mytest_test.go:17: MySuite.TestAssertEqualsSpeed
PASS: mytest_test.go:17: MySuite.TestAssertEqualsSpeed  5.288s

START: mytest_test.go:23: MySuite.TestAssertIsNilSpeed
PASS: mytest_test.go:23: MySuite.TestAssertIsNilSpeed   1.612s

START: mytest_test.go:30: MySuite.TestOrdinaryComparisonSpeed
PASS: mytest_test.go:30: MySuite.TestOrdinaryComparisonSpeed    0.004s

OK: 3 passed
--- PASS: Test (6.90s)
PASS
ok      bytemark.co.uk/auth3/auth/mytest    6.906s
```

Some loss of performance is to be expected, of course, but I don't believe this amount is expected or desirable. I can rearchitect the tests to avoid the large number of calls to c.Assert(), but hopefully it's just down to some unnecessary use of reflect or a copy or something that isn't needed.

**Comment by niemeyer** [comment]
I'm happy to have go-check become faster, and I would welcome patches that do that without compromising readability and clarity, but I'm not keen on micro-optimizing out _tiny_ differences that were introduced by the compiler itself. You are complaining about a function that takes 0.00000041 seconds to run in your tests.
