### ISSUE TITLE
Idea: provide a `context.Context` object to tests in the C object

### ISSUE THREAD

**Issue by Lucretiel** [go-check/check#88]
The idea is that you can write something like this:

    func (s* suite) TestSomething(c *C) {
        suiteCtx := c.SuiteContext()
        testCtx := c.TestContext()
    }

The `SuiteContext` is guaranteed to be cancelled at the end of the suite, and the `TestContext` is guaranteed to be cancelled at the end of the individual test. This is something that could be provided in a fixture, but it seems a shame to duplicate that in all my suites, and (as far as I know) there's no way to do "Suite mixins" or anything like that. In any case, I also wasn't sure what (if any) concurrency capabilities that GoCheck provides, and placing the `TestContext` object inside the suite would preclude its safe use in multiple parallel tests.

**Comment by Lucretiel** [comment]
Quick follow-up: this feature already exists in `testing` as [`testing.T.Context()`](https://tip.golang.org/pkg/testing/#T.Context). Is there a way to access the underlying `T` object during a gocheck test? If not, we should be able to use this as the basis for the `C.Context` method.

**Comment by niemeyer** [comment]
Having `T.Context` in 1.8 feels like a mistake, and for the same reason it'd also be a mistake to have it in go-check. Here is the reason, copied from my message to golang-dev:

> Such a flagging mechanism that by definition will only be useful when things will continue running in the background past the test completion does feel like a wart to me. We should be discouraging people from doing that in the first place, because arbitrary background logic delayed for arbitrary periods of time while other things are being tested is a common source of testing pain, breaking in curious and hard to reproduce ways.
>
> As people pointed out, it's not a mere case of putting logic locally. The context, by definition, will only trigger code to _start_ aborting after it's too late. An aborting yet running goroutine can do whatever it wants in order to attempt to stop cleanly.
>
> In my own testing, services generally have a Stop method because of that. Internally, they leverage a [tomb](https://gopkg.in/tomb.v2) to flag the stopping and block until everything is done cleaning themselves up. Stop also usually returns an error, so one can also check that the stop was itself clean.

**Comment by niemeyer** [comment]
Conversation about `T.Context` is taking place here: https://github.com/golang/go/issues/18199
